* Eco Feature Project Notes
** Creating features from other features
   Because the features are simply linear filters, the output of some filters can be used for others.
*** Creating every possible filtered image
    To speed up testing and training I thought that I could create filtered result for every possible filter that could exists.
    By limiting the genomes of the filters to a cap of 5,5,1,1 I still get good results and there are only 144 different possibilities.
** Testing every filter instead of random evolution 
   With a cap of 5,5,1,1 for the genome (x_blur,y_blur,x_diff,y_diff) there are only 144 possibilities. 
   Maybe it would improve performance to just check every possibility.
*** Random sampling
    Much of the eco feature algorithm uses random. I think it is used to reduce over fitting.
*** New algorithm
**** How to determine which filter is best
     The genetic algorithm used a smaller test set from the data set to determine fitness.
     Could I use the gini impurity?
     Maybe the size of the tree?
*** Profile the training time (filter and random forest)
    On i7 desktop with the fish data set, image processing takes an average of 15,000 cycles, where training the forest (5 trees 5 deep) takes about 53,000 cycles.
** Gini heat map
   Could I use the gini purity measure to figure out which 
** Using smaller Forests
*** Experiment 
    [[file:eco_config_results.org][Results from various configurations]]
** Using the same data set for training and testing creatures
   It seems that results are generally better and more consistant when data sets aren't split into train and hold sets
** Evaluation
   Get statistics of many training runs to see the tade
